[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Pointer vers les libs externalisées dans esp32_master
lib_extra_dirs = 
    ../esp32_master/lib

; Dépendances
lib_deps =
    ArduinoJson@6.21.2

; Optimisation
build_flags = 
    -O2
    -DCORE_DEBUG_LEVEL=3
